baseURL: https://jobnmadu.com/
languageCode: en
defaultContentLanguage: en
title: Modeling to develop...
theme: stip-hugo
HeaderUsername = "overlord"
HeaderHostname = "jobnmadu.com"
disableKinds:
  - page
  - section
  - taxonomy
  - taxonomyTerm
Author:
  bio: Professor of Agricultural Economics
  name: Job Nmadu
params:
  [menu]
    [[menu.header]]
      name = "posts"
      weight = 0
      url = "/posts"
  links:
    - icon: envelope
      iconset: fas
      title: E-mail
      url: mailto:job.nmadu@gmail.com
    - icon: github
      title: Github
      url: https://github.com/JobNmadu
    - icon: twitter
      title: Twitter
      url: https://twitter.com/JobNmadu
    - icon: linkedin
      title: LinkedIn
      url: https://www.linkedin.com/in/jobnmadu
    - icon: telegram
      title: Telegram
      url: https://t.me/Job_Nmadu
    - icon: blogger
      title: Blogger
      url: https://jobnmadu.blogspot.com/
    - icon: https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16
      title: ORCID iD
      url: https://orcid.org/0000-0002-1320-8957      
    - icon: google scholar
      title: Scholar
      url: http://scholar.google.com/citations?user=C1_-HgIAAAAJ&hl=en
