baseURL: https://jobnmadu.rbind.io/
languageCode: en
defaultContentLanguage: en
title: Modeling to develop...
theme: stip-hugo
disableKinds:
  - page
  - section
  - taxonomy
  - taxonomyTerm
Author:
  bio: Professor of Agricultural Economics
  name: Job Nmadu
params:
  links:
    - icon: envelope
      iconset: fas
      title: E-mail
      url: mailto:job.nmadu@gmail.com
    - icon: github
      title: Github
      url: https://github.com/JobNmadu
    - icon: twitter
      title: Twitter
      url: https://twitter.com/JobNmadu
    - icon: linkedin
      title: LinkedIn
      url: https://www.linkedin.com/in/jobnmadu
    - icon: orcid
      title: ORCiD iD
      url: iD https://orcid.org/0000-0002-1320-8957
    - icon: blogger
      title: Blogger
      url: https://jobnmadu.blogspot.com/

