---
title: "Criteria for assesing the adequacy of estimated models"
author: "Job Nmadu"
date: "1/14/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, comment="", dev="svg")#, #dev.args=list(type="cairo"))

source("docs/RegressionDiagnosis.R")
```

# Selection criteria for GLM types with numeric dependent variable

```{r echo = FALSE, message = FALSE, warning = FALSE}
clotting <- data.frame(
  u = c(5,10,15,20,30,40,60,80,100),
  lot1 = c(118,58,42,35,27,25,21,19,18),
  lot2 = c(69,35,26,21,18,16,13,12,12))
setosa <- glm(lot1 ~ log(u), data = clotting, family = Gamma)

GLMNum <- ModelSelection(Observed = clotting$lot1, Model = setosa, K =2,
                         Name = "nil", Form = "GLM", kutuf = 0,
                         TTy = "Number", Data = clotting)
GLMNum
```

# Selection criteria for GLM types with binary/categorical dependnet variables

```{r echo = FALSE, message = FALSE, warning = FALSE}

training.data.raw <- read.csv('data/titanic.csv',header=T,na.strings=c(""))
data <- subset(training.data.raw,select=c(2,3,5,6,7,8,10,12))
data <- subset(training.data.raw,select=c(2,3,5,6,7,8,10,12))
data <- data[!is.na(data$Embarked),]
rownames(data) <- NULL
train <- data[1:800,]
test <- data[801:889,]
model <- glm(Survived ~.,family=binomial(link='logit'),data=train)
GLMNN <- ModelSelection(Observed = train$Survived, Model = model, K =2,
                        Name = "nil", Form = "GLM", kutuf = 0, TTy = "NN",
                        Data = data)
GLMNN
```

# Selection criteria for LM types

```{r echo=FALSE, message=FALSE, warning=FALSE}

ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
WWWW <- as.data.frame(cbind(weight, group))
lm.D9 <- lm(weight ~ group)

LMNN <- ModelSelection(Observed = weight, Model = lm.D9, K =2,  Name = "nil",
                       Form = "LM", kutuf = 0, TTy = "NN", Data = WWWW)
LMNN
```

# Selection criteria for LM types with distribution link

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(greybox)
library(readxl)
Fake <- read_xlsx("data/fakeDATA.xlsx")
colnames(Fake) <- c("Farmincome", "Age", "Familysize", "Extensioncontacts",
                    "Numberofyearsinformaleducation", "Gender",
                    "accessroadtofarm", "Maritalstatus")

ALM_21 <- alm(Farmincome ~ Age + Familysize + Extensioncontacts +
                Numberofyearsinformaleducation + Gender + accessroadtofarm +
                Maritalstatus, data = Fake, distribution="pnorm")

ALMnn <- ModelSelection(Observed = Fake$Farmincome, Model = ALM_21, K =2,
                        Name = "nil", Form = "ALM", kutuf = 0, TTy = "Number",
                        Data = Fake)
ALMnn
```

# Selection criteria for ARDL

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(ARDL)
data("denmark", package = "ARDL")

ard <- ardl(LRM ~ LRY + IBO + IDE, data = denmark, order = c(3,1,3,2))
arlnum <- ModelSelection(Observed = lag(denmark$LRM, 3), Model = ard, K =2,
               Name = "nil", Form = "ARDL", kutuf = 0, TTy = "Number",
               Data = denmark)
arlnum
```


```{r echo = FALSE, message = FALSE, warning = FALSE}

SSSD <- as.data.frame(cbind("GLM with numeric depedent varaible" = GLMNum,"GLM with factor depedent varaible" = GLMNN,"Linear model"  = LMNN, "Augmented linear model" = ALMnn, "ARDL" = arlnum))

XYZ <- knitr::kable(SSSD, "html")
kableExtra::kable_styling(XYZ, "striped", position = "center")
```
